//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraceBack.Dal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_log
    {
        public System.Guid log_id { get; set; }
        public System.DateTime log_time { get; set; }
        public System.Guid log_user { get; set; }
        public string log_action_name { get; set; }
        public string log_message { get; set; }
        public int log_type { get; set; }
    }
}
